
import type { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  // Breakfast
  {
    id: 1,
    name: "Sunrise Scramble",
    description: "Telur orak-arik lembut dengan keju cheddar, daun bawang, dan roti panggang.",
    price: 187500,
    image: "https://placehold.co/600x400.png",
    aiHint: "scrambled eggs",
    category: "Breakfast",
  },
  {
    id: 2,
    name: "Classic Pancakes",
    description: "Tiga tumpuk panekuk buttermilk disajikan dengan sirup maple dan mentega.",
    price: 150000,
    image: "https://placehold.co/600x400.png",
    aiHint: "pancakes breakfast",
    category: "Breakfast",
  },
  {
    id: 3,
    name: "Avocado Toast",
    description: "Alpukat tumbuk di atas roti sourdough panggang, ditaburi serpihan paprika merah.",
    price: 146250,
    image: "https://placehold.co/600x400.png",
    aiHint: "avocado toast",
    category: "Breakfast",
  },
  {
    id: 14,
    name: "Hearty Oatmeal",
    description: "Oatmeal hangat dengan gula merah, kismis, dan sedikit kayu manis.",
    price: 112500,
    image: "https://placehold.co/600x400.png",
    aiHint: "oatmeal bowl",
    category: "Breakfast",
  },
  {
    id: 15,
    name: "Breakfast Burrito",
    description: "Telur orak-arik, sosis, keju, dan salsa dibungkus dengan tortilla hangat.",
    price: 165000,
    image: "https://placehold.co/600x400.png",
    aiHint: "breakfast burrito",
    category: "Breakfast",
  },
  {
    id: 24,
    name: "Belgian Waffles",
    description: "Wafel renyah dengan topping buah beri segar dan krim kocok.",
    price: 172500,
    image: "https://placehold.co/600x400.png",
    aiHint: "waffles berries",
    category: "Breakfast",
  },
  {
    id: 25,
    name: "Eggs Benedict",
    description: "Telur rebus dan bacon Kanada di atas muffin Inggris, disiram saus hollandaise.",
    price: 210000,
    image: "https://placehold.co/600x400.png",
    aiHint: "eggs benedict",
    category: "Breakfast",
  },
  {
    id: 26,
    name: "Fruit & Yogurt Parfait",
    description: "Lapisan yogurt Yunani, granola, dan aneka buah beri di dalam gelas tinggi.",
    price: 127500,
    image: "https://placehold.co/600x400.png",
    aiHint: "yogurt parfait",
    category: "Breakfast",
  },
  {
    id: 27,
    name: "Steak and Eggs",
    description: "Sarapan berat dengan steik sirloin 6oz, dua telur, dan kentang goreng.",
    price: 270000,
    image: "https://placehold.co/600x400.png",
    aiHint: "steak eggs",
    category: "Breakfast",
  },

  // Lunch
  {
    id: 4,
    name: "The Ronal Burger",
    description: "Patty daging sapi khas kami dengan selada, tomat, bawang, dan saus spesial.",
    price: 225000,
    image: "https://placehold.co/600x400.png",
    aiHint: "cheeseburger fries",
    category: "Lunch",
  },
  {
    id: 5,
    name: "Chicken Caesar Salad",
    description: "Dada ayam panggang, selada romaine, crouton, dan saus Caesar.",
    price: 213750,
    image: "https://placehold.co/600x400.png",
    aiHint: "chicken salad",
    category: "Lunch",
  },
  {
    id: 6,
    name: "Club Sandwich",
    description: "Sandwich tiga lapis dengan kalkun, bacon, selada, tomat, dan mayo.",
    price: 202500,
    image: "https://placehold.co/600x400.png",
    aiHint: "club sandwich",
    category: "Lunch",
  },
  {
    id: 16,
    name: "Veggie Wrap",
    description: "Hummus, mentimun, tomat, dan sayuran campur dalam tortilla bayam.",
    price: 180000,
    image: "https://placehold.co/600x400.png",
    aiHint: "veggie wrap",
    category: "Lunch",
  },
  {
    id: 17,
    name: "Soup of the Day",
    description: "Tanyakan pada pelayan kami untuk pilihan sup buatan sendiri yang lezat hari ini.",
    price: 97500,
    image: "https://placehold.co/600x400.png",
    aiHint: "bowl soup",
    category: "Lunch",
  },
  {
    id: 28,
    name: "Fish Tacos",
    description: "Tiga taco ikan dengan adonan ringan, selada kubis, pico de gallo, dan aioli chipotle.",
    price: 217500,
    image: "https://placehold.co/600x400.png",
    aiHint: "fish tacos",
    category: "Lunch",
  },
  {
    id: 29,
    name: "Margherita Flatbread",
    description: "Roti pipih renyah dengan mozzarella segar, tomat, dan basil.",
    price: 195000,
    image: "https://placehold.co/600x400.png",
    aiHint: "margherita pizza",
    category: "Lunch",
  },
  {
    id: 30,
    name: "Philly Cheesesteak",
    description: "Irisan tipis steik dengan bawang bombay panggang dan keju provolone leleh di atas roti hoagie.",
    price: 232500,
    image: "https://placehold.co/600x400.png",
    aiHint: "philly cheesesteak",
    category: "Lunch",
  },
  {
    id: 31,
    name: "Quinoa Salad",
    description: "Salad sehat dan menyegarkan dengan quinoa, buncis, mentimun, dan vinaigrette lemon.",
    price: 191250,
    image: "https://placehold.co/600x400.png",
    aiHint: "quinoa salad",
    category: "Lunch",
  },

  // Dinner
  {
    id: 7,
    name: "Grilled Salmon",
    description: "Fillet salmon panggang sempurna disajikan dengan asparagus dan lemon.",
    price: 330000,
    image: "https://placehold.co/600x400.png",
    aiHint: "grilled salmon",
    category: "Dinner",
  },
  {
    id: 8,
    name: "Steak Frites",
    description: "Steik sirloin yang juicy disajikan dengan porsi besar kentang goreng renyah.",
    price: 382500,
    image: "https://placehold.co/600x400.png",
    aiHint: "steak fries",
    category: "Dinner",
  },
  {
    id: 9,
    name: "Spaghetti Carbonara",
    description: "Pasta klasik dengan pancetta, telur, keju pecorino, dan lada hitam.",
    price: 270000,
    image: "https://placehold.co/600x400.png",
    aiHint: "pasta carbonara",
    category: "Dinner",
  },
  {
    id: 18,
    name: "Chicken Parmesan",
    description: "Dada ayam bertepung roti dengan saus marinara dan mozzarella, disajikan dengan spaghetti.",
    price: 300000,
    image: "https://placehold.co/600x400.png",
    aiHint: "chicken parmesan",
    category: "Dinner",
  },
  {
    id: 19,
    name: "Vegetarian Curry",
    description: "Campuran sayuran musiman dalam saus kari kelapa yang harum, disajikan dengan nasi.",
    price: 262500,
    image: "https://placehold.co/600x400.png",
    aiHint: "vegetable curry",
    category: "Dinner",
  },
  {
    id: 32,
    name: "Filet Mignon",
    description: "Fillet 8oz bagian tengah, dimasak sempurna, dengan kentang tumbuk dan buncis.",
    price: 480000,
    image: "https://placehold.co/600x400.png",
    aiHint: "filet mignon",
    category: "Dinner",
  },
  {
    id: 33,
    name: "Lobster Ravioli",
    description: "Ravioli buatan tangan diisi dengan daging lobster dalam saus saffron krim.",
    price: 390000,
    image: "https://placehold.co/600x400.png",
    aiHint: "lobster ravioli",
    category: "Dinner",
  },
  {
    id: 34,
    name: "Roast Duck",
    description: "Setengah bebek berkulit renyah dengan saus ceri dan nasi liar.",
    price: 420000,
    image: "https://placehold.co/600x400.png",
    aiHint: "roast duck",
    category: "Dinner",
  },
  {
    id: 35,
    name: "Mushroom Risotto",
    description: "Nasi Arborio creamy dengan jamur liar, keju parmesan, dan minyak truffle.",
    price: 285000,
    image: "https://placehold.co/600x400.png",
    aiHint: "mushroom risotto",
    category: "Dinner",
  },

  // Appetizers
  {
    id: 10,
    name: "Bruschetta",
    description: "Irisan baguette panggang dengan topping tomat segar, bawang putih, basil, dan minyak zaitun.",
    price: 127500,
    image: "https://placehold.co/600x400.png",
    aiHint: "bruschetta appetizer",
    category: "Appetizers",
  },
  {
    id: 11,
    name: "Crispy Calamari",
    description: "Cumi goreng tepung renyah disajikan dengan saus marinara yang segar.",
    price: 165000,
    image: "https://placehold.co/600x400.png",
    aiHint: "fried calamari",
    category: "Appetizers",
  },
  {
    id: 20,
    name: "Spinach Artichoke Dip",
    description: "Saus bayam dan artichoke creamy disajikan panas dengan keripik tortilla.",
    price: 142500,
    image: "https://placehold.co/600x400.png",
    aiHint: "spinach dip",
    category: "Appetizers",
  },
  {
    id: 21,
    name: "Mozzarella Sticks",
    description: "Stik mozzarella goreng keemasan dengan saus marinara klasik.",
    price: 120000,
    image: "https://placehold.co/600x400.png",
    aiHint: "mozzarella sticks",
    category: "Appetizers",
  },
  {
    id: 36,
    name: "Buffalo Wings",
    description: "Setengah lusin sayap ayam pedas disajikan dengan saus keju biru dan stik seledri.",
    price: 157500,
    image: "https://placehold.co/600x400.png",
    aiHint: "chicken wings",
    category: "Appetizers",
  },
  {
    id: 37,
    name: "Onion Rings",
    description: "Satu keranjang penuh bawang bombay goreng tepung bir, digoreng hingga renyah keemasan.",
    price: 112500,
    image: "https://placehold.co/600x400.png",
    aiHint: "onion rings",
    category: "Appetizers",
  },
  {
    id: 38,
    name: "Shrimp Cocktail",
    description: "Udang jumbo dingin disajikan dengan saus koktail yang tajam.",
    price: 187500,
    image: "https://placehold.co/600x400.png",
    aiHint: "shrimp cocktail",
    category: "Appetizers",
  },
  {
    id: 39,
    name: "Loaded Nachos",
    description: "Keripik tortilla dilumuri keju, jalapeño, krim asam, dan guacamole.",
    price: 172500,
    image: "https://placehold.co/600x400.png",
    aiHint: "nachos supreme",
    category: "Appetizers",
  },
  {
    id: 40,
    name: "Garlic Bread with Cheese",
    description: "Roti panggang Prancis dengan mentega bawang putih dan keju mozzarella leleh.",
    price: 90000,
    image: "https://placehold.co/600x400.png",
    aiHint: "garlic bread",
    category: "Appetizers",
  },

  // Desserts
  {
    id: 12,
    name: "Chocolate Lava Cake",
    description: "Kue cokelat hangat dengan lelehan di tengah, disajikan dengan es krim vanila.",
    price: 135000,
    image: "https://placehold.co/600x400.png",
    aiHint: "chocolate cake",
    category: "Desserts",
  },
  {
    id: 13,
    name: "New York Cheesecake",
    description: "Cheesecake kaya dan creamy dengan dasar biskuit graham.",
    price: 120000,
    image: "https://placehold.co/600x400.png",
    aiHint: "cheesecake slice",
    category: "Desserts",
  },
  {
    id: 22,
    name: "Classic Apple Pie",
    description: "Sepotong pai apel hangat dengan kulit renyah, disajikan a la mode.",
    price: 105000,
    image: "https://placehold.co/600x400.png",
    aiHint: "apple pie",
    category: "Desserts",
  },
  {
    id: 23,
    name: "Ice Cream Sundae",
    description: "Dua sendok es krim vanila dengan saus cokelat, krim kocok, dan ceri.",
    price: 90000,
    image: "https://placehold.co/600x400.png",
    aiHint: "ice cream sundae",
    category: "Desserts",
  },
  {
    id: 41,
    name: "Tiramisu",
    description: "Hidangan penutup klasik Italia dengan lapisan ladyfingers, mascarpone, dan espresso.",
    price: 127500,
    image: "https://placehold.co/600x400.png",
    aiHint: "tiramisu slice",
    category: "Desserts",
  },
  {
    id: 42,
    name: "Crème Brûlée",
    description: "Dasar custard yang kaya dengan lapisan gula karamel yang keras.",
    price: 142500,
    image: "https://placehold.co/600x400.png",
    aiHint: "creme brulee",
    category: "Desserts",
  },
  {
    id: 43,
    name: "Brownie a la Mode",
    description: "Brownie hangat dan legit dengan satu sendok es krim vanila dan saus cokelat.",
    price: 112500,
    image: "https://placehold.co/600x400.png",
    aiHint: "brownie ice cream",
    category: "Desserts",
  },
  {
    id: 44,
    name: "Key Lime Pie",
    description: "Pai asam manis dengan dasar biskuit graham dan krim kocok.",
    price: 105000,
    image: "https://placehold.co/600x400.png",
    aiHint: "key lime pie",
    category: "Desserts",
  },
  {
    id: 45,
    name: "Sorbet Trio",
    description: "Pilihan menyegarkan dari tiga rasa sorbet musiman.",
    price: 97500,
    image: "https://placehold.co/600x400.png",
    aiHint: "sorbet scoops",
    category: "Desserts",
  },

  // Drinks
  {
    id: 46,
    name: "Freshly Brewed Coffee",
    description: "Kopi panas yang baru diseduh, reguler atau tanpa kafein.",
    price: 45000,
    image: "https://placehold.co/600x400.png",
    aiHint: "cup coffee",
    category: "Drinks",
  },
  {
    id: 47,
    name: "Iced Tea",
    description: "Teh hitam yang baru diseduh dan didinginkan, disajikan dengan irisan lemon.",
    price: 45000,
    image: "https://placehold.co/600x400.png",
    aiHint: "glass iced tea",
    category: "Drinks",
  },
  {
    id: 48,
    name: "Soft Drinks",
    description: "Pilihan Coke, Diet Coke, Sprite, atau Ginger Ale.",
    price: 37500,
    image: "https://placehold.co/600x400.png",
    aiHint: "soda can",
    category: "Drinks",
  },
  {
    id: 49,
    name: "Fresh Orange Juice",
    description: "Jus jeruk segar yang baru diperas.",
    price: 67500,
    image: "https://placehold.co/600x400.png",
    aiHint: "orange juice",
    category: "Drinks",
  },
  {
    id: 50,
    name: "Homemade Lemonade",
    description: "Limun asam manis buatan sendiri.",
    price: 52500,
    image: "https://placehold.co/600x400.png",
    aiHint: "lemonade pitcher",
    category: "Drinks",
  },
  {
    id: 51,
    name: "Espresso",
    description: "Satu shot espresso yang kuat.",
    price: 52500,
    image: "https://placehold.co/600x400.png",
    aiHint: "espresso shot",
    category: "Drinks",
  },
  {
    id: 52,
    name: "Cappuccino",
    description: "Espresso dengan susu steamed dan lapisan busa yang tebal.",
    price: 67500,
    image: "https://placehold.co/600x400.png",
    aiHint: "cappuccino cup",
    category: "Drinks",
  },
  {
    id: 53,
    name: "Strawberry Smoothie",
    description: "Campuran creamy dari stroberi, pisang, dan yogurt.",
    price: 90000,
    image: "https://placehold.co/600x400.png",
    aiHint: "strawberry smoothie",
    category: "Drinks",
  },
  {
    id: 54,
    name: "Chocolate Milkshake",
    description: "Milkshake kental dan creamy yang dibuat dengan es krim cokelat.",
    price: 97500,
    image: "https://placehold.co/600x400.png",
    aiHint: "chocolate milkshake",
    category: "Drinks",
  }
];
